#!/bin/bash

set -e 
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
port -d -N selfupdate 
port -d -N upgrade outdated
# Twice for apple-gcc-42 for bootstrap.
port -d -N install \
    apple-gcc42 \
    apple-gcc42 \
    gcc16 \
    git \
    libsdl2 \
    openssh \
    openssl \
    openvpn2 \
    curl \
    libsdl \
    python314 \
    ffmpeg \
    aria2 \
    vim

# Optimized builds:
if [ "$(machine)" == "ppc970" ]; then
    sudo port -d -N install \
        ffmpeg +G4 \
        ffmpeg +G5 \
	mplayer +G4 \
	mplayer +G5
        mplayer
fi
