#!/bin/bash

set -e 
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
port -d -N selfupdate 
port -d -N upgrade outdated
# Twice for apple-gcc-42 for bootstrap.
port -d -N install \
    apple-gcc42 \
    apple-gcc42 \
    gcc16 \
    git \
    libsdl2 \
    openssh \
    openssl \
    openvpn2 \
    curl \
    libsdl \
    python314 \
    ffmpeg \
    aria2 \
    vim \
    bash \
    xorg \
    nano \
    wget \
    cmark

set +e
# Optimized builds:
if [ "$(machine)" == "ppc970" ]; then
    sudo port deactivate ffmpeg
    sudo port -d -N install ffmpeg +G4
    sudo port deactivate ffmpeg
    sudo port -d -N install ffmpeg +G5

    sudo port deactivate mplayer
    sudo port -d -N install mplayer

    sudo port deactivate mplayer
    sudo port -d -N install mplayer +G4

    sudo port deactivate mplayer
    sudo port -d -N install mplayer +G5
fi
