#!/bin/bash
priv_key="$HOME/tigerports-privkey.pem"

mkdir -p /var/www/html/macports/distfiles
sudo chown -R ${USER}:www-data /var/www/html/macports/distfiles
sudo find /var/www/html/macports/distfiles -type d -exec chmod 755 {} +
sudo find /var/www/html/macports/distfiles -type f -exec chmod 644 {} +

mkdir -p /var/www/html/macports/packages
sudo chown -R ${USER}:www-data /var/www/html/macports/packages
sudo find /var/www/html/macports/packages -type d -exec chmod 755 {} +
sudo find /var/www/html/macports/packages -type f -exec chmod 644 {} +
cd /var/www/html/tmp

find . -name "*.tbz2" | while read -r pkg_path; do
    echo "Signing: $pkg_path"
    openssl dgst -ripemd160 -sign "$priv_key" -out "${pkg_path}.rmd160" "$pkg_path"
done

# Stats. 
binary_archives_stats=/var/www/html/binary-archives-stats.txt
tiger_ppc_package_count=$(find . -iname "*8.ppc.tar.bz2" | wc -l)
tiger_i386_package_count=$(find . -iname "*8.i386.tar.bz2" | wc -l)
echo "Binary archives built for Tiger as of $date:" > $binary_archives_stats
echo "ppc: $tiger_ppc_package_count" >> $binary_archives_stats
echo "i386: $tiger_i386_package_count" >> $binary_archives_stats

# More 'instant' then straight scp into /var/www/html/macports/packages...
rm -rf /var/www/html/macports/packages/*
mv /var/www/html/tmp/* /var/www/html/macports/packages/
rm -rf /var/www/html/tmp/*
