#!/bin/bash
priv_key="$HOME/tigerports-privkey.pem"

mkdir -p /var/www/html/macports/distfiles
sudo chown -R ${USER}:www-data /var/www/html/macports/distfiles
sudo find /var/www/html/macports/distfiles -type d -exec chmod 755 {} +
sudo find /var/www/html/macports/distfiles -type f -exec chmod 644 {} +

mkdir -p /var/www/html/macports/packages
sudo chown -R ${USER}:www-data /var/www/html/macports/packages
sudo find /var/www/html/macports/packages -type d -exec chmod 755 {} +
sudo find /var/www/html/macports/packages -type f -exec chmod 644 {} +
cd /var/www/html/macports/packages

find . -name "*.tbz2" | while read -r pkg_path; do
    if [ ! -f "${pkg_path}.rmd160" ]; then
        echo "Signing: $pkg_path"
        openssl dgst -ripemd160 -sign "$priv_key" -out "${pkg_path}.rmd160" "$pkg_path"
    fi
done