#!/bin/bash
privkey="~/Desktop/tigerports/tigerports-privkey.pem"

mkdir -p ~/Desktop/tigerports
cp -rv /opt/local/var/macports/software ~/Desktop/tigerports/packages
cp -rv /opt/local/var/macports/distfiles ~/Desktop/tigerports/distfiles

cd ~/Desktop/tigerports/packages

find . -name "*.tbz2" | while read -r pkg_path; do
    if [ ! -f "${pkg_path}.rmd160" ]; then
        echo "Signing: $pkg_path"
        openssl dgst -ripemd160 -sign "$PRIVKEY_PATH" -out "${pkg_path}.rmd160" "$pkg_path"
    fi
done